version: "3.7"

services:
  # caddy:
  #   container_name: caddy
  #   image: docker.io/library/caddy:2-alpine
  #   network_mode: host
  #   restart: unless-stopped
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile:ro
  #     - caddy-data:/data:rw
  #     - caddy-config:/config:rw
  #   environment:
  #     - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-http://localhost}
  #     - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
  #   cap_drop:
  #     - ALL
  #   cap_add:
  #     - NET_BIND_SERVICE
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "1m"
  #       max-file: "1"

  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - valkey-data2:/data
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
      - searxng_secure
    # ports:
    #   - "127.0.0.1:8080:8080"
    volumes:
      - ${DATA_DIR}/searxng/data:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw
    env_file: .env
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-10}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-10}
      - tzinfos=America/Toronto
    # cap_drop:
    #   - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

    labels:
      # traefik enable
      - "traefik.enable=true"
      - "traefik.docker.network=searxng_secure"
      - "traefik.http.routers.searxng.rule=Host(`searxng.${DOMAIN}`)"
      - "traefik.http.routers.searxng.entrypoints=https"
      - "traefik.http.routers.searxng.priority=1"
      - "traefik.http.routers.searxng.tls=true"
      - "traefik.http.routers.searxng.service=searxng"
      - "traefik.http.routers.searxng.middlewares=chain-tinyauth-oauth@file"
      - "traefik.http.services.searxng.loadbalancer.server.port=8080"
networks:
  searxng:
  searxng_secure:
    external: true

volumes:
  valkey-data2:
  searxng-data:
