version: "3"
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    env_file: .env
    volumes:
      - ${DATA_DIR}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ha.rule=Host(`home.${DOMAIN}`)"
      - "traefik.http.routers.ha.entrypoints=https"
      - "traefik.http.routers.ha.tls=true"
      - "traefik.http.routers.ha.service=homeassistant-server@file"

      - "traefik.http.services.ha.loadBalancer.server.port=8123"
      - "traefik.http.services.ha.loadBalancer.passHostHeader=true"
    # networks:
    #   - traefik_network # Add this line

  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
    volumes:
      - ${DATA_DIR}/data/matter:/data
      - /run/dbus:/run/dbus:ro
    network_mode: host
    # networks:
    #   - traefik_network # Add this line

  music-assistant-server:
    image: ghcr.io/music-assistant/server:latest # <<< Desired release version here (or use beta to get the latest beta version)
    container_name: music-assistant-server
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    volumes:
      - ${DATA_DIR}/music-assistant-server/data:/data/
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    env_file: .env
    environment:
      - LOG_LEVEL=info
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ha-music.rule=Host(`music.${DOMAIN}`)"
      - "traefik.http.routers.ha-music.entrypoints=https"
      - "traefik.http.routers.ha-music.tls=true"
      - "traefik.http.routers.ha-music.service=ha-music-server@file"

      - "traefik.http.services.ha-music.loadBalancer.server.port=8095"
      - "traefik.http.services.ha-music.loadBalancer.passHostHeader=true"
      
networks:
  traefik_network:
    external: true
